Documentation: so2: Add survey section in the filesystems-part1 lab
linux-kernel-labs/linux pull request #271
Opened 2021-04-19 11:19 UTC by laurentiustefan97

Add a section in the filesystems-part1 lab (lab8) for the students to
complete the teaching survey created by the computer department.

Signed-off-by: Laurentiu Stefan <steflaurentiu@gmail.com>

2021-04-19 11:22 UTC, valighita commented on Documentation/teaching/so2/lab8-filesystems-part1.rst
> +   In order to have a better understanding of what we do well and we can do better, what factors affect your implication in teaching, extracurricular but also professional activities, we ask you to c
Please split this in multiple lines.

2021-04-19 11:34 UTC, laurentiustefan97 commented on Documentation/teaching/so2/lab8-filesystems-part1.rst
> +   In order to have a better understanding of what we do well and we can do better, what factors affect your implication in teaching, extracurricular but also professional activities, we ask you to c
Fixed it.

2021-04-19 11:35 UTC, valighita approved these changes

2021-04-19 12:40 UTC, razvand requested changes
I added feedback as suggestions.

2021-04-19 12:40 UTC, razvand commented on Documentation/teaching/so2/lab8-filesystems-part1.rst
> +   better, what factors affect your implication in teaching, extracurricular
```suggestion
   better, what factors affect your involvement in teaching, extracurricular
```

2021-04-19 12:40 UTC, razvand commented on Documentation/teaching/so2/lab8-filesystems-part1.rst
> +   but also professional activities, we ask you to complete `this survey
```suggestion
   and professional activities, we ask you to complete `this survey
```

2021-04-19 12:40 UTC, razvand commented on Documentation/teaching/so2/lab8-filesystems-part1.rst
> +   3-5 minutes. Obviously, we will send you the analysis of the survey and
```suggestion
   5-7 minutes. Obviously, we will send you the analysis of the survey and
```

2021-04-19 12:40 UTC, razvand commented on Documentation/teaching/so2/lab8-filesystems-part1.rst
> +   use it to improve the teaching activities.
```suggestion
   use it to improve our activities in the faculty.
```

2021-04-19 14:02 UTC, laurentiustefan97 commented
> I added feedback as suggestions.

@razvand I addressed the feedback.

2021-04-20 14:43 UTC, razvand approved these changes
All good.

2021-04-20 14:44 UTC, merged